#REF - https://www.bezkoder.com/docker-mern/

version: '3.8'

services:
  # FOR MONGODB SETUP
  # mongodb:
  #   image: mongo:5.0.2
  #   restart: unless-stopped
  #   env_file: ./.env
  #   environment:
  #     - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
  #     - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
  #   ports:
  #     - $MONGODB_LOCAL_PORT:$MONGODB_DOCKER_PORT
  #   volumes:
  #     - db:/data/db
  #   networks:
  #     - backend
  
  backend-api:
    # depends_on:
    #   - mongodb
    build: ./backend
    container_name: backend_container
    restart: unless-stopped
    env_file: ./backend/.env
    ports:
      - 5000:5000
    volumes: # VOLUMES allows us to use the hot reload functionality of NODEMON
      - ./backend:/backend
      - /backend/node_modules
    # environment:
    #   - DB_HOST=mongodb
    #   - DB_USER=$MONGODB_USER
    #   - DB_PASSWORD=$MONGODB_PASSWORD
    #   - DB_NAME=$MONGODB_DATABASE
    #   - DB_PORT=$MONGODB_DOCKER_PORT
    #   - CLIENT_ORIGIN=$CLIENT_ORIGIN
    # networks:
    #   - backend
    #   - frontend

  frontend-ui:
    depends_on:
      - backend-api
    build:
      context: ./frontend
      # args:
      #   - REACT_APP_API_BASE_URL=$CLIENT_API_BASE_URL
    container_name: frontend_container
    ports:
      - 3000:3000 # NOT NGINX
      #- 3000:80 # Make sure to use 80 on the SECOND PORT since it will be used by NGINX
    volumes: # VOLUMES allows us to use the hot reload functionality of NODEMON
      - ./frontend:/frontend
      - /frontend/node_modules
    # networks:
    #   - frontend  

volumes: 
  db:

networks:
  backend:
  frontend: